"""Deterministic transpiler: SketchSpec -> NCTI Python script.

No LLM involved. Given a valid SketchSpec, this always produces the same,
API-correct script (variable names derived from primitive ids). This is the
"结构化转译" layer: it eliminates syntax/API/naming errors by construction.
"""

from __future__ import annotations

from app.sketch.api_catalog import CONSTRAINT_API, GEOMETRY_API
from app.sketch.spec import Constraint, Primitive, SketchSpec


def _pt(p: tuple[float, float, float]) -> str:
    return f"NCTI.Point({p[0]}, {p[1]}, {p[2]})"


def _vec(v: tuple[float, float, float]) -> str:
    return f"NCTI.Vector({v[0]}, {v[1]}, {v[2]})"


# `skt` is the dynamically-bound NCTI SketchWorkPlane; attribute access below is
# intentional and not type-checked.
def _emit_primitive(p: Primitive) -> str:
    vid = p.id
    t = p.type
    if t == "point":
        return f"{vid} = skt.AddPoint({_pt(p.at)})"
    if t == "line":
        return f"{vid} = skt.AddLine({_pt(p.start)}, {_pt(p.end)})"
    if t == "centerline":
        return f"{vid} = skt.AddCenterLine({_pt(p.start)}, {_pt(p.end)})"
    if t == "spline":
        pts = ", ".join(_pt(x) for x in p.points)
        return f"{vid} = skt.AddSpline([{pts}])"
    if t == "rect":
        return f"{vid} = skt.AddRect({_pt(p.start)}, {_pt(p.end)})"
    if t == "circle":
        return f"{vid} = skt.AddCircle({_pt(p.center)}, {p.radius})"
    if t == "arc":
        if p.start is not None:
            return f"{vid} = skt.AddArc({_pt(p.start)}, {_pt(p.end)}, {_pt(p.point_on_arc)})"
        return f"{vid} = skt.AddArc({p.radius}, {p.start_angle}, {p.end_angle}, {_pt(p.center)})"
    if t == "ellipse":
        return f"{vid} = skt.AddEllipse({_pt(p.center)}, {_vec(p.major)}, {_vec(p.minor)})"
    if t == "ellipse_arc":
        return (
            f"{vid} = skt.AddEllipseArc({_pt(p.center)}, {_vec(p.major)}, {_vec(p.minor)}, "
            f"{p.start_angle}, {p.end_angle})"
        )
    if t == "fillet":
        return f"skt.CurveRadius({p.radius}, {p.line_a}, {p.line_b})"
    if t == "chamfer":
        return f"skt.CurveChamfer({p.dist_a}, {p.line_a}, {p.dist_b}, {p.line_b})"
    if t == "trim":
        if p.objects:
            objs = ", ".join(p.objects)
            return f"skt.CurveTrimming({_pt(p.at)}, [{objs}])"
        return f"skt.CurveTrimming({_pt(p.at)})"
    if t == "offset":
        objs = ", ".join(p.objects)
        return f"skt.CurveOffset([{objs}], {p.distance})"
    raise ValueError(f"unknown primitive type: {t}")


def _emit_constraint(c: Constraint) -> str:
    api = CONSTRAINT_API[c.type]
    t = c.type
    if t in ("length", "xpos", "ypos"):
        if c.target2 is not None:
            return f"skt.{api}({c.index or 0}, {c.target}, {c.index2 or 0}, {c.target2})"
        return f"skt.{api}({c.index or 0}, {c.target})"
    if t == "radius":
        return f"skt.{api}({c.target})"
    if t == "angle":
        if c.target2 is not None:
            return f"skt.{api}({c.target}, {c.target2})"
        return f"skt.{api}({c.target})"
    if t in ("parallel", "perpendicular", "tangent", "equal", "horizontal", "vertical"):
        if c.target2 is not None:
            return f"skt.{api}({c.target}, {c.target2})"
        return f"skt.{api}({c.target})"
    if t == "coincide":
        if c.target2 is not None:
            return f"skt.{api}({c.index or 0}, {c.target}, {c.index2 or 0}, {c.target2})"
        return f"skt.{api}({c.index or 0}, {c.target})"
    raise ValueError(f"unknown constraint type: {t}")


def transpile(spec: SketchSpec) -> str:
    """Compile a SketchSpec into an executable NCTI Python script string."""
    lines: list[str] = []
    lines.append("# Auto-generated by NCTI Sketch Transpiler (deterministic, API-frozen)")
    lines.append("yh_doc = YH.YHDocument(doc)")
    if not spec.auto_solve:
        lines.append("yh_doc.AutoSolve(False)")
        lines.append("yh_doc.AutoCalFreeCons(False)")
        lines.append("yh_doc.AutoCalCloseArea(False)")
    lines.append("skt = YH.SketchWorkPlane(doc)")
    lines.append("skt.Open()")
    lines.append("")
    for p in spec.primitives:
        lines.append(_emit_primitive(p))
    if spec.constraints:
        lines.append("")
        for c in spec.constraints:
            lines.append(_emit_constraint(c))
    lines.append("")
    lines.append("skt.RunSolve()")  # always solve at end (manual solve when auto_solve off)
    lines.append("skt.Close()")
    return "\n".join(lines)
